version: '3'
services:

  # React用のコンテナ
  front:
    build:
      context: ./MagicBox/React/
    volumes: 
      - ./MagicBox/React:/src
    command: 'npm start'
    ports:
      - "3000:3000"

  # Rails用のコンテナ
  back:
    build:
      context: ./MagicBox/Rails/
    volumes: 
      - ./MagicBox/Rails:/app
    ports:
      - "3100:3100"