version: '3'
services:

  # React用のコンテナ
  front:
    build:
      context: ./MagicBox/React/
    volumes: 
      - ./MagicBox/React:/src
    ports:
      - "3000:3000"

  # Rails用のコンテナ
  back:
    build:
      context: ./MagicBox/Rails/
    volumes: 
      - ./MagicBox/Rails:/app
    ports:
      - "3100:3100"

  auth:
    build:
      context: ./MagicBox/Auth/
    volumes: 
      - ./MagicBox/Auth:/app
    ports:
      - "3200:3200"

  # MySQL用のコンテナ
  db:
    image: mysql:8.0.33
    volumes:
      - data-volume:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
    ports:
      - 3306:3306

volumes:
  data-volume: