#syntax=docker/dockerfile:1
FROM alpine

# パッケージをインストール
RUN apk update && \
    apk --no-cache add git 

RUN git clone https://github.com/nematatu/nematatu.github.io.git 
#CMD ["git","clone","https://github.com/nematatu/nematatu.github.io.git"]
# プライベートリポジトリをクローン